# Generated by Django 4.0.4 on 2022-04-20 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogAgeCalcualtorSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_value', models.PositiveIntegerField()),
                ('size_label', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Calculator Dog Size',
            },
        ),
        migrations.CreateModel(
            name='DogAgeCalcualtorYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_value', models.PositiveIntegerField()),
                ('year_label', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Dog Age Year Number',
            },
        ),
        migrations.CreateModel(
            name='DogAgeCalcualtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_result', models.PositiveIntegerField()),
                ('body', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('year_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_num', to='toolcalculate.dogagecalcualtoryear')),
                ('year_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='year_size', to='toolcalculate.dogagecalcualtorsize')),
            ],
            options={
                'verbose_name_plural': 'Dog Age Calculator',
            },
        ),
    ]
