# Generated by Django 4.0.3 on 2022-03-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='body',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
