# Generated by Django 4.0.3 on 2022-03-15 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sites.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_website_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to=sites.models.user_directory_path, verbose_name='book_thumbnail')),
                ('slug', models.SlugField(max_length=100)),
                ('excerpt', models.TextField(blank=True, max_length=150, null=True)),
                ('body', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=7)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.AddField(
            model_name='website',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=sites.models.user_directory_path, verbose_name='logo'),
        ),
        migrations.CreateModel(
            name='Bookpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=100)),
                ('excerpt', models.TextField(blank=True, max_length=150, null=True)),
                ('body', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('public', 'Public'), ('draft', 'Draft')], default='draft', max_length=7)),
                ('views', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Book Page',
            },
        ),
    ]
