# Generated by Django 4.0.3 on 2022-03-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_book_website_logo_bookpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
