# Generated by Django 4.0.3 on 2022-03-15 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_alter_book_body_alter_bookpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='website', to='sites.website'),
        ),
    ]
